# This is a basic workflow to help you get started with Actions
name: CI/CD

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install discord
          pip install boto3
          pip install pytest
      - name: Run tests
        run: pytest --rootdir=tests
  deploy_process:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy Processing LAMBDA
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v0.1.0
      - name: Zip Processing
        run: zip -qq -r ./processing.zip *
        working-directory: lambdas/processing
      - name: Zip bot code into processing
        run: zip -r lambdas/processing/processing.zip ./uamtbot
      - name: Deploy processing to LAMBDA
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: uamtBotProcessingLambda
          zip_file: lambdas/processing/processing.zip
  deploy_inter:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy Interactions LAMBDA
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v0.1.0
      - name: Zip interactions
        run: zip -qq -r ./interaction.zip *
        working-directory: lambdas/interaction
      - name: Zip bot code into processing
        run: zip -r lambdas/processing/interaction.zip ./uamtbot
      - name: Deploy interaction Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: uamtBotInteractionBasicLambda
          zip_file: lambdas/interaction/interaction.zip
