# This is a basic workflow to help you get started with Actions
name: Unit tests

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytest
      - name: Run tests
        run: pytest --rootdir=tests
  deploy_source:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: build and deploy lambda
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v0.1.0
      - name: Zip Processing
        run: zip -qq -r ../processing.zip *
        working-directory: processing
      - name: Zip bot code into processing
        run: zip -r processing.zip ./uamtbot
      - name: Deploy processing to LAMBDA
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: uamtBotProcessingLambda
          zip_file: processing.zip
