# This is a basic workflow to help you get started with Actions

name: Processing LAMBDA

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   deploy_source:
       name: build and deploy lambda
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v1
        - uses: montudor/action-zip@v0.1.0
        - name: zip processing
          run: zip -qq -r ../procesing.zip *
          working-directory: processing
        - name: zip interaction
          run: zip -qq -r ../interaction.zip *
          working-directory: interaction
        - name: deploy processing
          uses: appleboy/lambda-action@master
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: us-east-1
            function_name: uamtBotProcessingLambda
            zip_file: processing.zip
        - name: deploy interaction
          uses: appleboy/lambda-action@master
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: us-east-1
            function_name: uamtBotInteractionBasicLambda
            zip_file: interaction.zip
