# This is a basic workflow to help you get started with Actions
name: Unit tests

# Controls when the workflow will run
on: [push, pull_request]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          command: pytest
          args: --rootdir=tests
